src/ExtendedXmlSerializer/ContentModel/Collections/CollectionContentOption.cs
src/ExtendedXmlSerializer/ContentModel/Collections/CollectionContentsReader.cs
src/ExtendedXmlSerializer/ContentModel/Collections/CollectionItemReader.cs
src/ExtendedXmlSerializer/ContentModel/Collections/DictionaryContentsReader.cs
src/ExtendedXmlSerializer/ContentModel/Collections/ICollectionItemReader.cs
src/ExtendedXmlSerializer/ContentModel/Collections/MemberedCollectionItemReader.cs
src/ExtendedXmlSerializer/ContentModel/Content/DictionaryContentOption.cs
src/ExtendedXmlSerializer/ContentModel/Content/DictionaryEntries.cs
src/ExtendedXmlSerializer/ContentModel/Content/IDictionaryEntries.cs
src/ExtendedXmlSerializer/ContentModel/Members/MemberContentsReader.cs
src/ExtendedXmlSerializer/ContentModel/Members/MemberedContentOption.cs
src/ExtendedXmlSerializer/ContentModel/Properties/TypeParser.cs
src/ExtendedXmlSerializer/ContentModel/Xml/AssemblyTypePartitions.cs
src/ExtendedXmlSerializer/ContentModel/Xml/GenericTypes.cs
src/ExtendedXmlSerializer/ContentModel/Xml/IdentityPartitionedTypes.cs
src/ExtendedXmlSerializer/ContentModel/Xml/PartitionedTypes.cs
src/ExtendedXmlSerializer/TypeModel/ApplicationTypeSpecification.cs
src/ExtendedXmlSerializer/TypeModel/ApplicationTypes.cs
src/ExtendedXmlSerializer/TypeModel/AssemblyPublicTypes.cs
src/ExtendedXmlSerializer/TypeModel/AssemblyTypes.cs
src/ExtendedXmlSerializer/TypeModel/IAssemblyTypes.cs

A few issues I had to solve with collection properties that impacted performance.  We're holding at 33us/45us on my machine ATM.

Performance adjustments.

---

src/ExtendedXmlSerializer/ContentModel/Members/DefaultMemberContents.cs
src/ExtendedXmlSerializer/ExtensionModel/Content/Members/AlteredMemberContents.cs
src/ExtendedXmlSerializer/ExtensionModel/Encryption/EncryptedConverter.cs
src/ExtendedXmlSerializer/ExtensionModel/Encryption/EncryptionExtension.cs
test/ExtendedXmlSerializer.Tests/Configuration/ConfigurationContainerTests.cs
test/ExtendedXmlSerializer.Tests/ExtensionModel/Encryption/EncryptionExtensionTests.cs
test/ExtendedXmlSerializer.Tests/Support/SerializationSupport.cs

Making a PR to review and accept.

Breaking Change: Fixing how encryption handles member format. #122.

---

test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue218Tests.cs

this is related to the issue #218.

Add failing test for issue 218

---

.gitattributes
src/ExtendedXmlSerializer/ContentModel/Conversion/TypeParts.cs
src/ExtendedXmlSerializer/ContentModel/Members/MemberDescriptor.cs
src/ExtendedXmlSerializer/ContentModel/Reflection/AssemblyPath.cs
src/ExtendedXmlSerializer/ContentModel/Reflection/Key.cs
src/ExtendedXmlSerializer/ContentModel/Reflection/MemberParts.cs
src/ExtendedXmlSerializer/Core/Delimiter.cs
src/ExtendedXmlSerializer/ExtensionModel/Coercion/CoercerParameter.cs
src/ExtendedXmlSerializer/ExtensionModel/Content/ContentAlteration.cs
src/ExtendedXmlSerializer/ExtensionModel/Expressions/Evaluation.cs
src/ExtendedXmlSerializer/ExtensionModel/Instances/Existing.cs
src/ExtendedXmlSerializer/ExtensionModel/Instances/InstanceReader.cs
src/ExtendedXmlSerializer/ExtensionModel/Markup/MarkupExtensionAwareSerializer.cs
src/ExtendedXmlSerializer/ExtensionModel/References/Identifier.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceIdentity.cs
src/ExtendedXmlSerializer/ExtensionModel/SurrogatesExtension.cs
src/ExtendedXmlSerializer/ReflectionModel/TypePartition.cs

Additional housekeeping commits.

Issues/issue272 #272

---

.build/Common.ps1
.build/Success.ps1
appveyor.yml

Removing personal access token.

Deployment Key Implementation

---

.build/Success.ps1
appveyor.yml

- Testing out PR publishing to preview feed as preview packages (e.g. `2.1.24.400-tvanugbn-preview`).
- Commits to `master` publish to preview feed (e.g. `2.1.24.400`)

Build Script Adjustments

---

.build/appveyor.yml

build: Adjust build script location.

---

.github/issue-branch.yml

ci: Configure issue branch creation.

---

.build/Install.ps1
.build/Success.ps1
.build/appveyor.yml

Enables deployment release to GitHub whenever a new release is tagged, created, and built.
Releases will be found here:
https://github.com/ExtendedXmlSerializer/ExtendedXmlSerializer/releases
Closes #304

ci: Deploy to GitHub on Release

---

src/ExtendedXmlSerializer/ExtendedXmlSerializer.csproj
test/ExtendedXmlSerializer.Tests.ReportedIssues/ExtendedXmlSerializer.Tests.ReportedIssues.csproj
test/ExtendedXmlSerializer.Tests/ExtendedXmlSerializer.Tests.csproj

Upgraded minimum .NET version to 4.5.2

---

.build/Prepare-Deployment.ps1
documentation/index.md
src/ExtendedXmlSerializer/ExtendedXmlSerializer.csproj

Fixed deployment issues

---

src/ExtendedXmlSerializer/ExtendedXmlSerializer.csproj
test/ExtendedXmlSerializer.Tests.ReportedIssues/ExtendedXmlSerializer.Tests.ReportedIssues.csproj
test/ExtendedXmlSerializer.Tests/ExtendedXmlSerializer.Tests.csproj

Updated NuGet references.

---

src/ExtendedXmlSerializer/Configuration/TypeContentCompositionRegistrationContext.cs
src/ExtendedXmlSerializer/Configuration/TypeRegistrationContext.cs
src/ExtendedXmlSerializer/ExtensionMethods.cs
src/ExtendedXmlSerializer/ExtensionMethodsForAlteration.cs
src/ExtendedXmlSerializer/ExtensionMethodsForXml.cs
src/ExtendedXmlSerializer/ExtensionModel/Content/RegisteredCompositionExtension.cs
src/ExtendedXmlSerializer/ExtensionModel/Xml/Activated.cs
src/ExtendedXmlSerializer/ExtensionModel/Xml/ActivatedSerializer.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue264Tests.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue346Tests.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue346Tests_Custom.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue349Tests.cs

Improved content serializer composition API.

---

src/ExtendedXmlSerializer/Configuration/ContextBase.cs
src/ExtendedXmlSerializer/Configuration/TypeRegistrationContext.cs
src/ExtendedXmlSerializer/Configuration/TypeSerializationRegistrationContext.cs
src/ExtendedXmlSerializer/Configuration/TypeSerializerComposerRegistrationContext.cs
src/ExtendedXmlSerializer/Core/Sources/CompositeAlteration.cs
src/ExtendedXmlSerializer/Core/Sources/ReferenceCacheBase.cs
src/ExtendedXmlSerializer/Core/Sources/SpecificationSource.cs
src/ExtendedXmlSerializer/Core/Sources/StructureCacheBase.cs
src/ExtendedXmlSerializer/Core/Sources/TableSource.cs
src/ExtendedXmlSerializer/Core/Specifications/AllSpecification.cs
src/ExtendedXmlSerializer/Core/Specifications/DecoratedSpecification.cs
src/ExtendedXmlSerializer/Core/Specifications/DelegatedSpecification.cs
src/ExtendedXmlSerializer/ExtensionMethodsForAlteration.cs
src/ExtendedXmlSerializer/ExtensionModel/Registrations.cs
src/ExtendedXmlSerializer/ExtensionModel/Xml/DefaultMemberOrder.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue264Tests.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue346Tests_Custom.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue349Tests.cs

Further improved serializer registration

---

src/ExtendedXmlSerializer/ExtensionModel/Content/Members/ConstructorMembers.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue355Tests.cs

Added ordering to parameterized content members.

---

src/ExtendedXmlSerializer/ExtensionModel/References/RootReferences.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue355Tests.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue358Tests.cs

Accounted for struct root instances when references are enabled.

---

src/ExtendedXmlSerializer/ContentModel/Content/DynamicAwareSerializers.cs
src/ExtendedXmlSerializer/ContentModel/Reflection/TypeNameFormatter.cs
src/ExtendedXmlSerializer/ExtensionModel/SerializationExtension.cs
src/ExtendedXmlSerializer/ReflectionModel/IsAnonymousType.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue288Tests.cs

Added basic (throw) support for anonymous/dynamic types.

---

src/ExtendedXmlSerializer/ContentModel/Reflection/AssemblyPathParser.cs
src/ExtendedXmlSerializer/ContentModel/Reflection/AssemblyTypePartitions.cs
src/ExtendedXmlSerializer/ContentModel/Reflection/Classification.cs
src/ExtendedXmlSerializer/ContentModel/Reflection/Types.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue431Tests.cs
test/ExtendedXmlSerializer.Tests/ContentModel/Reflection/TypePartsParserTests.cs

Allowed `null`/Empty Namespaces for Custom/Non-system Assemblies

---

.build/appveyor.yml

Update NuGet API Key

---

test/ExtendedXmlSerializer.Tests.Performance/Program.cs

Use BenchmarkSwitcher

---

src/ExtendedXmlSerializer/ExtendedXmlSerializer.csproj
test/ExtendedXmlSerializer.Tests.Performance/Benchmarks.cs
test/ExtendedXmlSerializer.Tests.Performance/ExtendedXmlSerializer.Tests.Performance.csproj
test/ExtendedXmlSerializer.Tests.ReportedIssues/ExtendedXmlSerializer.Tests.ReportedIssues.csproj
test/ExtendedXmlSerializer.Tests/ExtendedXmlSerializer.Tests.csproj

In this PR I fixed:
* Update nuget packages
* fix ExtendedXmlSerializer.Tests.ReportedIssues for .NET 4.5.2

Update nuget packages

---

src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceEncounters.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue454Tests.cs

Scoped reference encounter counter to per-writer.

---

src/ExtendedXmlSerializer/ContentModel/Content/DictionaryEntries.cs
src/ExtendedXmlSerializer/Core/DictionaryPairTypes.cs
src/ExtendedXmlSerializer/ReflectionModel/DictionaryAdapters.cs
src/ExtendedXmlSerializer/ReflectionModel/DictionaryAddDelegates.cs
src/ExtendedXmlSerializer/ReflectionModel/DictionaryEnumerators.cs
src/ExtendedXmlSerializer/ReflectionModel/DictionaryPairTypesLocator.cs
src/ExtendedXmlSerializer/ReflectionModel/IDictionaryPairTypesLocator.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue463Tests.cs

Added basic support for custom `IDictionary<TKey, TValue>`.

---

test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue475Tests.cs

Demonstration of `Ignore` method.

---

test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue479Tests.cs

Test CI Template Message

---

test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue477Tests_Extended.cs

Attended to warnings.

---

src/ExtendedXmlSerializer/ExtensionModel/Content/UnknownContentHandlingExtension.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue473Tests.cs

Fixed list support in `WithUnknownContent`

---

src/ExtendedXmlSerializer/ExtensionMethodsForXml.cs
src/ExtendedXmlSerializer/ExtensionModel/Xml/MigrationsExtension.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue483Tests.cs

Added non-generic equivalent for `AddMigration`

---

src/ExtendedXmlSerializer/ContentModel/Members/FixedInstanceMemberSerialization.cs
src/ExtendedXmlSerializer/ContentModel/Members/IInstanceMemberSerialization.cs
src/ExtendedXmlSerializer/ContentModel/Members/InstanceMemberSerialization.cs
src/ExtendedXmlSerializer/ContentModel/Members/MemberInnerContentHandler.cs
src/ExtendedXmlSerializer/ExtensionModel/Content/UnknownContentHandlingExtension.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue491Tests.cs

Applied serializer type check using `WithUnknownContent`

---

src/ExtendedXmlSerializer/ExtensionMethodsForExtensionModel.cs
src/ExtendedXmlSerializer/ExtensionModel/References/IgnoreReferenceCheckExtension.cs
src/ExtendedXmlSerializer/ExtensionModel/References/StaticReferenceCheckingExtension.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue511Tests.cs

Added `ConfigurationContainer.EnableStaticReferenceChecking`

---

src/ExtendedXmlSerializer/ContentModel/Content/IRecursionContents.cs
src/ExtendedXmlSerializer/ContentModel/Content/Recursion.cs
src/ExtendedXmlSerializer/ContentModel/Content/RecursionAwareContents.cs
src/ExtendedXmlSerializer/ContentModel/Content/RecursionContents.cs
src/ExtendedXmlSerializer/ExtensionMethodsForExtensionModel.cs
src/ExtendedXmlSerializer/ExtensionModel/DefaultExtensions.cs
src/ExtendedXmlSerializer/ExtensionModel/RecursionAwareExtension.cs
src/ExtendedXmlSerializer/ExtensionModel/References/IgnoreReferenceCheckExtension.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ReferencesExtension.cs
src/ExtendedXmlSerializer/ExtensionModel/References/StaticReferenceCheckingExtension.cs
src/ExtendedXmlSerializer/ExtensionModel/SerializationExtension.cs
src/ExtendedXmlSerializer/ExtensionModel/ThreadAwareRecursionContentExtension.cs
src/ExtendedXmlSerializer/ExtensionModel/Xml/CustomSerializationExtension.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue511Tests.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue513Tests.cs

Added `ConfigurationContainer.EnableThreadAwareRecursionContent`

---

src/ExtendedXmlSerializer/ExtensionMethodsForContent.cs
src/ExtendedXmlSerializer/ExtensionModel/Content/AllowedTypesExtension.cs
src/ExtendedXmlSerializer/ExtensionModel/Xml/FormatReaderContexts.cs
src/ExtendedXmlSerializer/ExtensionModel/Xml/MigrationsExtension.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue515Tests.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue517Tests.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Shared/Issue517/Class1.cs

Fixed namespace resolution bug in migration extension

---

src/ExtendedXmlSerializer/ContentModel/Format/FormattedContent.cs
src/ExtendedXmlSerializer/ExtensionModel/Xml/XmlWriter.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue528Tests.cs

Adjusted writer to properly store root/default namespace

---

test/ExtendedXmlSerializer.Tests/ExtensionModel/References/ReferencesExtensionTests.cs

Added test to verify previous XML reads

---

.build/appveyor.yml

Build Nudge

---

src/ExtendedXmlSerializer/ContentModel/Reflection/VariableTypeWalker.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ProcessReference.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ProcessReferenceInput.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceAwareSerializers.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceBoundary.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceCompleted.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceResult.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceSet.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceView.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceWalker.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue583Tests.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue584Tests.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue98Tests.cs

Improved reference tracking for multiple instances

---

src/ExtendedXmlSerializer/ExtensionModel/Instances/ExistingInstanceExtension.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue599Tests.cs

Removed target instances from cache after first access

---

src/ExtendedXmlSerializer/ExtensionModel/References/ContainsStaticReferenceSpecification.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ProcessReference.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceAwareSerializers.cs
src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceSet.cs
test/.External/VweCore/Geometry/LineEquation.cs
test/.External/VweCore/Geometry/MapExtensions.cs
test/.External/VweCore/Geometry/Rectangle2D.cs
test/.External/VweCore/Map.Entities.cs

Attended to warnings

---

.build/appveyor.yml

Update GitHub API token

---

.build/Deploy-Documentation.ps1

Update to RSA

---

samples/ExtendedXmlSerializer.Samples/ExtendedXmlSerializer.Samples.csproj
test/ExtendedXmlSerializer.Tests.Performance/ExtendedXmlSerializer.Tests.Performance.csproj
test/ExtendedXmlSerializer.Tests.ReportedIssues.Issue502/ExtendedXmlSerializer.Tests.ReportedIssues.Issue502.csproj
test/ExtendedXmlSerializer.Tests.ReportedIssues/ExtendedXmlSerializer.Tests.ReportedIssues.csproj
test/ExtendedXmlSerializer.Tests/ExtendedXmlSerializer.Tests.csproj

Removed .NET6&7 and replaced with .NET8

---

src/ExtendedXmlSerializer/ContentModel/Collections/CollectionSpecification.cs
src/ExtendedXmlSerializer/ContentModel/Identification/Identities.cs
src/ExtendedXmlSerializer/ContentModel/Reflection/GenericNameParser.cs
src/ExtendedXmlSerializer/ExtensionModel/DefaultExtensions.cs
src/ExtendedXmlSerializer/ExtensionModel/GeneratedListAwareExtension.cs
src/ExtendedXmlSerializer/ExtensionModel/GeneratedSubstitute.cs
src/ExtendedXmlSerializer/ExtensionModel/IsGeneratedList.cs
src/ExtendedXmlSerializer/ReflectionModel/CollectionAwareConstructorLocator.cs
src/ExtendedXmlSerializer/ReflectionModel/IsCollectionTypeExpandedSpecification.cs
src/ExtendedXmlSerializer/ReflectionModel/IsUnspeakable.cs
test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue637Tests.cs

Enable support for generated lists
